import {
    ImageIcon,
    FileText,
    FileCode,
    FileJson,
    Package,
    Music,
    Video,
    Settings,
    Database,
    Archive,
    GitBranch,
} from "lucide-react"

import type { FileIcon } from "@/types/interfaces"

// File Icons
export const FILE_ICONS: Record<string, FileIcon> = {
    // Images
    png: { icon: ImageIcon, color: "text-blue-500" },
    jpg: { icon: ImageIcon, color: "text-blue-500" },
    jpeg: { icon: ImageIcon, color: "text-blue-500" },
    gif: { icon: ImageIcon, color: "text-blue-500" },
    svg: { icon: ImageIcon, color: "text-blue-500" },
    webp: { icon: ImageIcon, color: "text-blue-500" },
    heic: { icon: ImageIcon, color: "text-blue-500" },
    heif: { icon: ImageIcon, color: "text-blue-500" },

    // Documents
    pdf: { icon: FileText, color: "text-red-500" },
    doc: { icon: FileText, color: "text-blue-600" },
    docx: { icon: FileText, color: "text-blue-600" },
    txt: { icon: FileText, color: "text-gray-600" },
    md: { icon: FileText, color: "text-gray-600" },
    xlsx: { icon: FileText, color: "text-green-500" },
    xls: { icon: FileText, color: "text-green-500" },
    csv: { icon: FileText, color: "text-green-500" },
    pptx: { icon: FileText, color: "text-red-500" },
    ppt: { icon: FileText, color: "text-red-500" },
    ppsx: { icon: FileText, color: "text-red-500" },
    pps: { icon: FileText, color: "text-red-500" },

    // Code
    js: { icon: FileCode, color: "text-yellow-500" },
    jsx: { icon: FileCode, color: "text-blue-500" },
    ts: { icon: FileCode, color: "text-blue-600" },
    tsx: { icon: FileCode, color: "text-blue-600" },
    html: { icon: FileCode, color: "text-orange-500" },
    css: { icon: FileCode, color: "text-blue-400" },
    scss: { icon: FileCode, color: "text-pink-500" },
    json: { icon: FileJson, color: "text-yellow-600" },
    yaml: { icon: FileJson, color: "text-red-400" },
    yml: { icon: FileJson, color: "text-red-400" },
    py: { icon: FileCode, color: "text-green-500" },
    cpp: { icon: FileCode, color: "text-green-500" },
    c: { icon: FileCode, color: "text-green-500" },
    java: { icon: FileCode, color: "text-red-500" },
    kotlin: { icon: FileCode, color: "text-red-500" },
    swift: { icon: FileCode, color: "text-yellow-500" },
    go: { icon: FileCode, color: "text-blue-500" },
    rust: { icon: FileCode, color: "text-red-500" },
    php: { icon: FileCode, color: "text-purple-500" },
    ruby: { icon: FileCode, color: "text-red-500" },
    perl: { icon: FileCode, color: "text-red-500" },
    scala: { icon: FileCode, color: "text-red-500" },
    dart: { icon: FileCode, color: "text-blue-500" },
    cs: { icon: FileCode, color: "text-red-500" },
    csproj: { icon: FileCode, color: "text-red-500" },
    cshtml: { icon: FileCode, color: "text-red-500" },
    csx: { icon: FileCode, color: "text-red-500" },

    // Archives
    zip: { icon: Archive, color: "text-yellow-600" },
    rar: { icon: Archive, color: "text-yellow-600" },
    "7z": { icon: Archive, color: "text-yellow-600" },
    tar: { icon: Archive, color: "text-yellow-600" },
    gz: { icon: Archive, color: "text-yellow-600" },
    "tar.gz": { icon: Archive, color: "text-yellow-600" },
    "tar.xz": { icon: Archive, color: "text-yellow-600" },
    "tar.bz2": { icon: Archive, color: "text-yellow-600" },
    "tar.7z": { icon: Archive, color: "text-yellow-600" },
    "tar.zst": { icon: Archive, color: "text-yellow-600" },
    "tar.zstd": { icon: Archive, color: "text-yellow-600" },

    // Media
    mp3: { icon: Music, color: "text-green-500" },
    wav: { icon: Music, color: "text-green-500" },
    mp4: { icon: Video, color: "text-purple-500" },
    mov: { icon: Video, color: "text-purple-500" },
    avi: { icon: Video, color: "text-purple-500" },
    mkv: { icon: Video, color: "text-purple-500" },
    wmv: { icon: Video, color: "text-purple-500" },
    flv: { icon: Video, color: "text-purple-500" },
    m4v: { icon: Video, color: "text-purple-500" },
    m4a: { icon: Video, color: "text-purple-500" },
    m4b: { icon: Video, color: "text-purple-500" },

    // Others
    exe: { icon: Settings, color: "text-gray-500" },
    sh: { icon: Settings, color: "text-gray-500" },
    sql: { icon: Database, color: "text-blue-500" },
    db: { icon: Database, color: "text-blue-500" },
    ".env": { icon: Settings, color: "text-gray-500" },
    ".gitignore": { icon: GitBranch, color: "text-gray-500" },
    ".git": { icon: GitBranch, color: "text-gray-500" },

    // Package files
    "package.json": { icon: Package, color: "text-red-500" },
    "composer.json": { icon: Package, color: "text-blue-500" },
    "requirements.txt": { icon: Package, color: "text-green-500" },
    "pyproject.toml": { icon: Package, color: "text-green-500" },
    "Dockerfile": { icon: Package, color: "text-green-500" },
    "docker-compose.yml": { icon: Package, color: "text-green-500" },
    "entrypoint.sh": { icon: Package, color: "text-green-500" },
    "alembic.ini": { icon: Package, color: "text-green-500" },
    "alembic": { icon: Package, color: "text-green-500" },
    "alembic_versions": { icon: Package, color: "text-green-500" },
    "alembic_env.py": { icon: Package, color: "text-green-500" },
    "alembic_script.py.mako": { icon: Package, color: "text-green-500" },
}               